name: gojek_sederhana
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  art_sweetalert: ^0.0.5
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  latlong2: ^0.9.0
  path: ^1.8.3
  sqflite: ^2.3.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
